FROM golang:1.21-alpine

  # Install git
RUN set -ex; \
apk update; \
apk add --no-cache git

  # Set working directory
WORKDIR /go/src/github.com/pennsieve/rehydration-service

  # Run tests
CMD CGO_ENABLED=0 ./run-tests.sh
